Repository associatedemployers/granite, pull requests merged in 2018-11, with the labels that each got.

#366 added functionality for editing locations
  app/controllers/account/anatomy/location/edit.js
  app/router.js
  app/routes/account/anatomy/location/edit.js
  app/templates/account/anatomy/location/edit.hbs
  app/templates/components/list-item/location-item.hbs
Labels: review

#364 added functionality for editing departments
  app/controllers/account/anatomy/department/edit.js
  app/controllers/account/anatomy/department/new.js
  app/router.js
  app/routes/account/anatomy/department/edit.js
  app/templates/account/anatomy/department/edit.hbs
  app/templates/components/list-item/department-item.hbs
Labels: hacktoberfest, review

#381 added ability to disregard census column
  app/templates/account/employees/add/census/review.hbs
Labels: review

#327 edit recruiting process for specific campaign
  app/components/list-item/document-item.js
  app/controllers/account/documents/index.js
  app/controllers/account/job-opening/campaign/settings.js
  app/controllers/account/job-opening/setup/settings.js
  app/models/employee.js
  app/router.js
  app/routes/account/job-opening/campaign/settings.js
  app/routes/account/job-opening/setup/settings.js
  app/styles/granite/components/pipeline.less
  app/styles/granite/page/campaign-setup.less
  app/styles/granite/page/settings.less
  app/templates/account/job-opening/campaign/settings.hbs
  app/templates/account/job-opening/setup/settings.hbs
  mirage/config.js
  mirage/factories/action-item.js
  mirage/factories/applicant.js
  mirage/factories/asset-item.js
  mirage/factories/asset.js
  mirage/factories/department.js
  mirage/factories/departments.js
  mirage/factories/employee.js
  mirage/factories/employees.js
  mirage/factories/file.js
  mirage/factories/job-application.js
  mirage/factories/job-opening.js
  mirage/factories/location.js
  mirage/factories/locations.js
  mirage/factories/permission.js
  mirage/models/action-item.js
  mirage/models/applicant.js
  mirage/models/asset-item.js
  mirage/models/asset.js
  mirage/models/comment.js
  mirage/models/department.js
  mirage/models/file.js
  mirage/models/job-application.js
  mirage/models/job-opening.js
  mirage/models/job.js
  mirage/models/location.js
  mirage/models/permission.js
  package.json
  tests/acceptance/action-items/action-item-test.js
  tests/acceptance/action-items/action-items-test.js
  tests/acceptance/action-items/edit-action-item-test.js
  tests/acceptance/company-users-test.js
  tests/acceptance/custom-pipeline/custom-pipeline-settings-test.js
  tests/acceptance/custom-pipeline/custom-pipeline-setup-test.js
  tests/acceptance/documents-test.js
  tests/acceptance/employee-test.js
  tests/acceptance/employees-test.js
  tests/acceptance/recruiting/applicants-test.js
  tests/acceptance/recruiting/campaigns-test.js
  tests/acceptance/recruiting/recent-activity-test.js
  tests/unit/routes/account/document/index-test.js
  yarn.lock
Labels: review

#386 Try browserstack
  .travis.yml
  mirage/config.js
  package.json
  testem.js
  yarn.lock
Labels: review

#375 [Enhancement] #356 dropdown exempt or non exempt employee/job
  app/templates/account/employee/index/edit/job.hbs
Labels: awaiting submitter action, review
