Repository associatedemployers/granite, pull requests merged in 2018-07, with the labels that each got.

#252 adding a screening question does not duplicate
  app/controllers/account/job-opening/setup/screening.js
Labels: awaiting submitter action, review

#238 Add assets and categories while onboarding or editing employee
  app/components/modals/add-asset-category.js
  app/components/modals/ats-add-applicant.js
  app/controllers/account/employee/index/equipment.js
  app/controllers/account/employee/onboard/equipment.js
  app/routes/account/employee/index/equipment.js
  app/routes/account/employee/onboard/equipment.js
  app/templates/account/employee/index/equipment.hbs
  app/templates/account/employee/onboard/equipment.hbs
  app/templates/components/input/equipment-picker.hbs
  app/templates/components/list-item/assigned-asset-item.hbs
  app/templates/components/modals/add-asset-category.hbs
  tests/integration/components/modals/add-asset-category-test.js
Labels: review

#245 Added option for rejection letter to be sent up disqualified job application
  app/models/job-application.js
  app/styles/granite/components/modals/ats-confirm-disqualify.less
  app/styles/granite/components/pipeline.less
  app/templates/components/card-pipeline/stage-card.hbs
  app/templates/components/modals/ats-confirm-disqualify.hbs
Labels: on hold, review

#263 [Enhancements] Add address, company name. Remove palette
  app/controllers/account/settings/index/index.js
  app/templates/account/settings/index/index.hbs
Labels: review

#256 added a call us tag
  app/templates/account/employee/index/counseling/issue/new.hbs
Labels: awaiting submitter action, review

#264 [Feature] Product page
  .eslintrc.js
  app/components/display/product/features-list.js
  app/components/display/scroll-reveal.js
  app/controllers/our-product.js
  app/router.js
  app/routes/our-product.js
  app/styles/granite/components/elements/nav.less
  app/styles/granite/page/about.less
  app/styles/granite/page/our-product.less
  app/templates/about.hbs
  app/templates/about/pricing.hbs
  app/templates/components/display/product/features-list.hbs
  app/templates/components/display/scroll-reveal.hbs
  app/templates/components/elements/x-navigation.hbs
  app/templates/features.hbs
  app/templates/index.hbs
  app/templates/our-product.hbs
  ember-cli-build.js
  package.json
  public/assets/images/about_background.jpg
  public/assets/images/human-capital-blur.jpg
  public/assets/images/product-screenshots/applicant-tracking.png
  public/assets/images/product-screenshots/ats-onboarding.png
  public/assets/images/product-screenshots/automated-communications.png
  public/assets/images/product-screenshots/automated-job-listings.png
  public/assets/images/product-screenshots/careers-page.png
  public/assets/images/product-screenshots/custom-attributes.png
  public/assets/images/product-screenshots/custom-fields.png
  public/assets/images/product-screenshots/document-issues.jpg
  public/assets/images/product-screenshots/employee-info.png
  public/assets/images/product-screenshots/issue-corrective-actions.png
  public/assets/images/product-screenshots/offboarding-assets.png
  public/assets/images/product-screenshots/offboarding-assets1.png
  public/assets/images/product-screenshots/offboarding.png
  public/assets/images/product-screenshots/offboarding1.png
  public/assets/images/product-screenshots/organize-assets.png
  public/assets/images/product-screenshots/pre-screening.png
  public/assets/images/product-screenshots/scheduling.png
  public/assets/images/product_background-1.jpg
  public/assets/images/product_background-2.jpg
  tests/integration/components/display/product/features-list-test.js
  tests/integration/components/display/scroll-reveal-test.js
  tests/unit/controllers/our-product-test.js
  tests/unit/routes/our-product-test.js
  yarn.lock
Labels: review

#270 set default avatar so that no undefined requests take place
  app/components/display/employee-picture.js
Labels: review

#268 document assign works as it should, dropzone clears after uploading document
  app/controllers/account/documents/index.js
  app/controllers/account/documents/new.js
Labels: review

#261 bughancement/259 application should transition to login if session ti…
  app/components/confirm-modal.js
  app/controllers/application.js
  app/templates/application.hbs
Labels: awaiting submitter action, review

#250 [Enhancement] #212 add more explanation to the "delete record" confirma…
  app/templates/account/action-item.hbs
  app/templates/account/anatomy/company-users/index.hbs
  app/templates/account/asset.hbs
  app/templates/account/employee/index.hbs
  app/templates/account/employee/index/counseling/issue.hbs
  app/templates/account/employee/index/counseling/issue/corrective-action.hbs
  app/templates/account/employee/offboard/reorganization.hbs
  app/templates/account/job-description.hbs
  app/templates/account/job-opening/campaign.hbs
  app/templates/components/confirm-modal.hbs
  app/templates/components/list-item/department-item.hbs
  app/templates/components/list-item/document-item.hbs
  app/templates/components/list-item/location-item.hbs
  app/templates/components/modals/ats-confirm-disqualify.hbs
Labels: awaiting submitter action, review
