Repository associatedemployers/granite, pull requests merged in 2018-12, with the labels that each got.

#378 [Bug] #354 White text to dark when theme includes top white gradient …
  app/controllers/application.js
  app/styles/granite/components/elements/account-nav.less
  app/styles/granite/page/employee.less
  app/templates/application.hbs
  yarn.lock
Labels: review

#376 [Bug] [Regression] #330 Mobile styles for nav are screwy
  app/styles/granite/components/elements/nav.less
Labels: awaiting submitter action, review

#394 urlPrefix should be unique
  app/components/elements/account-navigation.js
  app/components/input/document-selection-modal.js
  app/components/validated-input.js
  app/controllers/signup.js
  app/mixins/ajax-status.js
  app/styles/granite/page/signup.less
  app/templates/account/employees/add/census/review.hbs
  app/templates/components/validated-input.hbs
  app/templates/signup/index.hbs
  package.json
  tests/acceptance/assets-test.js
  tests/acceptance/recruiting/new-position-test.js
  tests/acceptance/recruiting/recent-activity-test.js
  tests/acceptance/signup-test.js
Labels: awaiting submitter action, bug, review

#403 assets are suggested based on employee's job
  app/controllers/account/employee/onboard/equipment.js
  app/controllers/account/job-opening/campaign/applicant-tracking.js
  app/models/employee.js
  app/routes/account/employee/onboard/equipment.js
  app/routes/account/employee/onboard/job-information.js
  app/templates/account/employee/onboard/equipment.hbs
  app/templates/account/employee/onboard/job-information.hbs
  app/templates/components/input/equipment-picker.hbs
  yarn.lock
Labels: review

#404 added onboarding and offboarding tags for documents
  app/controllers/account/documents/new.js
Labels: review

#405 [Feature] Document assignment workflow in onboarding
  app/components/list-item/document-assignment.js
  app/components/list-item/document-suggestion.js
  app/controllers/account/employee/onboard/documents.js
  app/models/file-assignment.js
  app/router.js
  app/routes/account/employee/onboard.js
  app/routes/account/employee/onboard/documents.js
  app/styles/granite/ui/checkbox.less
  app/templates/account/employee/onboard/documents.hbs
  app/templates/components/list-item/document-assignment.hbs
  app/templates/components/list-item/document-suggestion.hbs
  tests/unit/controllers/account/employee/onboard/documents-test.js
  tests/unit/routes/account/employee/onboard/documents-test.js
Labels: review

#406 [Feature] #395 add upload to document selection modal
  app/components/input/document-selection-modal.js
  app/controllers/account/employee/offboard/options.js
  app/controllers/account/employee/onboard/documents.js
  app/styles/granite/components/document-selector.less
  app/templates/account/employee/offboard/options.hbs
  app/templates/account/employee/onboard/documents.hbs
  app/templates/components/input/document-selection-modal.hbs
Labels: feature, review

#409 [Bug] Fix breadcrumbs '/' to adjust to the background color.
  app/styles/granite/components/elements/account-nav.less
  app/styles/granite/global/application.less
  app/styles/granite/page/employee.less
Labels: bug, review

#408 [Feature] #336 associated documents on assets
  app/components/input/document-selection-modal.js
  app/controllers/account/asset/documents.js
  app/controllers/account/employee/onboard/equipment.js
  app/models/asset-item.js
  app/models/asset.js
  app/routes/account/employee/onboard/equipment.js
  app/styles/granite/components/pipeline.less
  app/styles/granite/global/segments.less
  app/templates/account/asset/documents.hbs
  app/templates/account/asset/index/new.hbs
  app/templates/account/assets/new.hbs
  app/templates/account/employee/onboard/equipment.hbs
  app/templates/components/input/document-selection-modal.hbs
Labels: feature, review

#392 Dropzone not working
  app/components/modals/ats-add-applicant.js
Labels: awaiting submitter action, bug, review

#411 documents in offboarding
  app/controllers/account/employee/offboard/documents.js
  app/router.js
  app/routes/account/employee/offboard.js
  app/routes/account/employee/offboard/documents.js
  app/templates/account/employee/offboard/documents.hbs
Labels: review

#388 Add 'zoom' to the org chart
  app/components/visualizations/organization-tree.js
  app/components/visualizations/reorganization-tree.js
Labels: enhancement, review

#380 wrote test for document page
  app/controllers/account/document.js
  mirage/config.js
  mirage/factories/company-user.js
  mirage/factories/file-assignment.js
  mirage/factories/file.js
  mirage/models/file-assignment.js
  tests/acceptance/documents/document-test.js
  tests/acceptance/documents/documents-test.js
  yarn.lock
Labels: awaiting submitter action, review

#427 [Feature] Talent pool MVP
  app/components/list-item/talent-pool-applicant.js
  app/controllers/account/employee/offboard/documents.js
  app/controllers/account/job-description.js
  app/controllers/account/job-opening/campaign/talent-pool.js
  app/mixins/route-abstractions/resource.js
  app/router.js
  app/routes/account/job-opening/campaign/talent-pool.js
  app/styles/granite/global/flex.less
  app/templates/account/job-opening/campaign.hbs
  app/templates/account/job-opening/campaign/index.hbs
  app/templates/account/job-opening/campaign/talent-pool.hbs
  app/templates/components/list-item/talent-pool-applicant.hbs
  mirage/config.js
  tests/acceptance/recruiting/recent-activity-test.js
  tests/acceptance/recruiting/talent-pool-test.js
  tests/integration/components/list-item/talent-pool-applicant-test.js
  tests/unit/controllers/account/job-opening/campaign/talent-pool-test.js
  tests/unit/routes/account/job-opening/campaign/talent-pool-test.js
Labels: review

#385 [Feature] add departments and locations during census upload
  app/components/census/dry-run-employee-relationship.js
  app/components/census/table-cell.js
  app/controllers/account/employees/add/census/review.js
  app/routes/account/employees/add/census/review.js
  app/templates/account/employees/add/census/review.hbs
  app/templates/components/census/dry-run-employee-relationship.hbs
  app/templates/components/census/table-cell.hbs
  app/templates/components/list-item/dry-run-employee.hbs
Labels: review

#433 [Fix] Transition scroll position
  app/router.js
  config/environment.js
  package.json
  tests/acceptance/company-users-test.js
  tests/acceptance/documents/document-test.js
  yarn.lock
Labels: review

#435 [Fix] Custom fields in census
  app/controllers/account/employees/add/census/review.js
  app/styles/granite/page/census-upload.less
  app/templates/account/employees/add/census/review.hbs
Labels: review

#437 [Enhancement] Swap exclusion model for corrective actions
  .travis.yml
  app/controllers/account/employee/index/counseling/new.js
  app/models/employee-issue.js
  app/routes/account/employee/index/counseling/new.js
Labels: review
