Repository associatedemployers/granite, pull requests merged in 2018-10, with the labels that each got.

#324 census upload now displays
  app/controllers/account/employees/add/census/review.js
  app/templates/account/employees/add/census/review.hbs
Labels: review

#331 [Enhancement] ATS drag/sort improvements, mobile styling, and some bug fixes
  .eslintrc.js
  CHANGELOG.md
  app/components/card-pipeline.js
  app/components/card-pipeline/stage-column.js
  app/components/list-item/event-item.js
  app/components/modals/index.js
  app/initializers/handle-deprecation-warnings.js
  app/mixins/ajax-status.js
  app/styles/common/variables.less
  app/styles/granite/components/pipeline.less
  app/templates/application.hbs
  app/templates/components/card-pipeline.hbs
  app/templates/components/card-pipeline/stage-card.hbs
  app/templates/components/card-pipeline/stage-column.hbs
  config/environment.js
  ember-cli-build.js
  package.json
  yarn.lock
Labels: review

#306 #303 employee/employees tests
  app/components/intro-js.js
  app/templates/account/employee/index/index.hbs
  mirage/config.js
  mirage/factories/departments.js
  mirage/factories/employees.js
  mirage/factories/locations.js
  mirage/models/asset-items.js
  mirage/models/departments.js
  mirage/models/locations.js
  tests/acceptance/employee-test.js
  tests/acceptance/employees-test.js
Labels: review

#329 commenting on activity is not duplicated any longer
  app/components/list-item/activity-item.js
Labels: review

#343 [Enhancement] Migrate from bower
  .bowerrc
  bower.json
  ember-cli-build.js
  package.json
  yarn.lock
Labels: hacktoberfest, review

#358 [Fix] Ajax status
  app/mixins/ajax-status.js
Labels: review

#313 [Testing] #309 Action items
  app/components/intro-js.js
  mirage/config.js
  mirage/factories/action-items.js
  mirage/models/action-items.js
  tests/acceptance/action-items-test.js
  tests/acceptance/action-items/action-item-test.js
  tests/acceptance/action-items/action-items-test.js
  tests/acceptance/action-items/edit-action-item-test.js
  tests/acceptance/action-items/new-action-item-test.js
  tests/acceptance/employee-test.js
  tests/acceptance/employees-test.js
Labels: review

#362 unify card design under anatomy
  app/templates/account/anatomy/company-users/index.hbs
  app/templates/account/anatomy/departments/index.hbs
  app/templates/account/anatomy/locations/index.hbs
  app/templates/components/list-item/department-item.hbs
  app/templates/components/list-item/location-item.hbs
  app/templates/components/list-item/user-item.hbs
Labels: hacktoberfest, review

#359 [Testing]#328 Documents
  app/controllers/account/settings/index/processes.js
  app/mixins/ajax-status.js
  app/routes/account/settings/index/processes.js
  app/routes/application.js
  app/utils/object-array-is-dirty.js
  mirage/config.js
  mirage/factories/action-items.js
  mirage/factories/company-user.js
  mirage/factories/departments.js
  mirage/factories/employees.js
  mirage/factories/files.js
  mirage/factories/locations.js
  mirage/models/action-items.js
  mirage/models/asset-items.js
  mirage/models/assets.js
  mirage/models/comments.js
  mirage/models/company-user.js
  mirage/models/company.js
  mirage/models/departments.js
  mirage/models/files.js
  mirage/models/job-openings.js
  mirage/models/locations.js
  mirage/serializers/application.js
  package.json
  tests/acceptance/action-items-test.js
  tests/acceptance/action-items/action-item-test.js
  tests/acceptance/action-items/action-items-test.js
  tests/acceptance/action-items/edit-action-item-test.js
  tests/acceptance/documents-test.js
  tests/acceptance/employee-test.js
  tests/acceptance/employees-test.js
  tests/acceptance/login-test.js
  tests/acceptance/recruiting/applicants-test.js
  tests/acceptance/recruiting/campaigns-test.js
  tests/acceptance/recruiting/new-position-test.js
  tests/acceptance/recruiting/recent-activity-test.js
  tests/acceptance/settings/processes-test.js
  tests/acceptance/signup-test.js
  tests/helpers/auth.js
  yarn.lock
Labels: hacktoberfest, review

#367 Sauce labs overage cancellation
  .travis.yml
  package.json
  yarn.lock
Labels: review

#368 removed unneeded dependency
  package.json
Labels: review

#373 removed slate payroll import options from location/department pages
  app/templates/account/anatomy/departments/index.hbs
  app/templates/account/anatomy/locations/index.hbs
Labels: review

#372 sort and filters for campaigns
  app/controllers/account/recruiting/index/index.js
  app/routes/account/recruiting/index/index.js
  app/templates/account/recruiting/index/index.hbs
Labels: review

#370 no more duplicate likes on activities
  app/components/list-item/activity-item.js
Labels: review

#369 loading status for census dry run
  app/templates/account/employees/add/census/review.hbs
Labels: review

#371 state selector won't highlight green on the bottom anymore
  app/styles/site/elements/input.overrides
  app/templates/signup/index.hbs
  tests/acceptance/signup-test.js
Labels: review

#374 fixed default payRateType on employee model
  app/models/employee.js
Labels: review

#322 moved some things around on assets page, added pagination
  app/controllers/account/asset/index.js
  app/routes/account/asset/index.js
  app/templates/account/asset.hbs
  app/templates/account/asset/index.hbs
  app/templates/components/list-item/asset-stock-item.hbs
Labels: awaiting submitter action, review

#297 added document page for view into specific document
  app/components/list-item/document-item.js
  app/components/list-item/file-assignment.js
  app/config/breadcrumb.js
  app/controllers/account/document.js
  app/controllers/account/document/index.js
  app/controllers/account/documents/index.js
  app/models/file-assignment.js
  app/router.js
  app/routes/account/document.js
  app/routes/account/document/index.js
  app/styles/granite/components/list-item/file-assignment.less
  app/templates/account/document.hbs
  app/templates/account/document/index.hbs
  app/templates/account/documents/index.hbs
  app/templates/components/list-item/document-item.hbs
  app/templates/components/list-item/file-assignment.hbs
  tests/unit/routes/account/document/index-test.js
Labels: awaiting submitter action, review
