Repository associatedemployers/granite, pull requests merged in 2019-04, with the labels that each got.

#557 [Bug][Rollbar] TypeError Cannot read property 'replace' of null
  app/models/job-opening.js
Labels: bug

#541 [Feature] Deactivate company users
  app/components/list-item/user-item.js
  app/controllers/account/anatomy/company-users/index.js
  app/models/company-user.js
  app/routes/account/anatomy/company-users/index.js
  app/templates/account/anatomy/company-users/index.hbs
  app/templates/components/list-item/user-item.hbs
Labels: review

#540 [Bug] Link color in employee summary (dark text) is not perfect for every case
  app/controllers/application.js
  app/styles/granitestyles/global/application.less
Labels: bug, review

#572 [Feature] Probation tracking
  app/controllers/account/employee/index/index.js
  app/controllers/account/settings/index/processes.js
  app/models/company.js
  app/models/employee.js
  app/styles/granitestyles/global/input.less
  app/templates/account/employee/index/index.hbs
  app/templates/account/settings/index/index.hbs
  app/templates/account/settings/index/processes.hbs
  app/templates/components/list-item/employee-item.hbs
  tests/acceptance/employee-test.js
  yarn.lock
Labels: feature
