Repository associatedemployers/granite, pull requests merged in 2019-02, with the labels that each got.

#481 [Fix] asset sharable toggle
  app/components/modals/add-asset-category.js
  app/controllers/account/assets/new.js
  app/templates/account/assets/new.hbs
  app/templates/components/modals/add-asset-category.hbs
Labels: review

#449 [Enhancement] Editing allowed in job summary
  app/controllers/account/job-description/edit.js
  app/router.js
  app/routes/account/job-description/edit.js
  app/templates/account/job-description.hbs
  app/templates/account/job-description/edit.hbs
  app/templates/components/input/quick-form-input.hbs
  tests/acceptance/job-descriptions/job-description-edit-test.js
Labels: awaiting submitter action, enhancement, review

#486 [Fix] changes for supervisor census lookup
  app/components/census/dry-run-employee-relationship.js
  app/components/census/table-cell.js
  app/templates/components/census/dry-run-employee-relationship.hbs
Labels: review

#480 [Fix] campaign setup notification drop downs
  app/controllers/account/anatomy/company-users/new.js
Labels: review

#465 [Enhancement] Move the employee search in org chart to the top
  app/templates/account/anatomy/index.hbs
Labels: awaiting submitter action, review

#462 [Bug] Remove links from steps in signup
  app/styles/granitestyles/page/signup.less
  app/templates/components/display/ui-step.hbs
Labels: awaiting submitter action, bug, review

#494 [Feature] EEO Visual ID
  app/config/forms/eeo.js
  app/controllers/account/employee/index/visual-id.js
  app/router.js
  app/routes/account/employee/index.js
  app/routes/account/employee/index/visual-id.js
  app/templates/account/employee/index.hbs
  app/templates/account/employee/index/visual-id.hbs
  tests/unit/controllers/account/employee/index/visual-id-test.js
  tests/unit/routes/account/employee/index/visual-id-test.js
Labels: review

#495 [Fix] continue campaign setup flag
  app/routes/account/job-opening/campaign.js
Labels: review

#496 [Enhancement] remove employee job route
  app/routes/account/employee/index/job.js
  app/templates/account/employee/index/job.hbs
Labels: review

#487 remove send applicant confirmation flag and property from model
  app/controllers/account/job-opening/campaign/settings.js
  app/controllers/account/job-opening/setup/settings.js
  app/models/job-opening.js
  app/templates/account/job-description.hbs
  app/templates/account/job-description/edit.hbs
  mirage/config.js
  mirage/factories/job.js
  tests/acceptance/company-users-test.js
  tests/acceptance/job-descriptions/job-description-edit-test.js
  tests/acceptance/recruiting/recent-activity-test.js
  tests/unit/controllers/account/employee/index/visual-id-test.js
  tests/unit/routes/account/employee/index/visual-id-test.js
Labels: review

#497 [Enhancement] no file assignments available text
  app/templates/account/employee/index/documents/index.hbs
Labels: review

#452 [Feature] Add job application notes field & "add todo" dropdown exclude term
  app/components/modals/add-notes.js
  app/controllers/account/job-opening/campaign/job-application/index.js
  app/models/job-application.js
  app/templates/account/job-opening/campaign/job-application/index.hbs
  app/templates/components/modals/add-notes.hbs
  app/templates/components/modals/ats-add-applicant.hbs
Labels: awaiting submitter action, feature, review

#484 [Enhancement] Add "Company Logo" label for dropzone in settings
  app/templates/account/settings/index/index.hbs
Labels: enhancement, review

#499 [Fix] no screening questions
  app/controllers/account/job-opening/setup/screening.js
Labels: review

#502 [Enhancement] Make error pages look professional
  app/styles/granitestyles/page/errors.less
  app/styles/granitestyles/ui/heros.less
  app/templates/catchall.hbs
  app/templates/error.hbs
  app/templates/not-found.hbs
  app/templates/unauthorized.hbs
  public/assets/images/401.jpg
  public/assets/images/404.jpg
  public/assets/images/500.jpg
Labels: review

#468 [Enhancement] Allow asset stock attribute editing
  app/controllers/account/asset/index.js
  app/controllers/account/asset/index/edit.js
  app/models/asset-item.js
  app/router.js
  app/routes/account/asset/index/edit.js
  app/templates/account/asset/index.hbs
  app/templates/account/asset/index/edit.hbs
  app/templates/components/list-item/asset-stock-item.hbs
  mirage/config.js
  tests/acceptance/asset/asset-item-edit-test.js
  tests/acceptance/asset/assets-test.js
Labels: enhancement, review

#501 [Enhancement] link job description on employee page
  app/routes/account/employee/index/edit/job.js
  app/templates/account/employee/index.hbs
  app/templates/account/employee/index/edit/job.hbs
Labels: review

#471 [Bug] Last cell isn't red on an invalid row & census overflow
  app/components/display/visual-overflow-table.js
  app/styles/common/variables.less
  app/styles/granitestyles/page/census-upload.less
  app/styles/site/globals/site.variables
  app/templates/account/asset/index.hbs
  app/templates/account/asset/index/edit.hbs
  app/templates/account/employees/add/census/review.hbs
  app/templates/components/list-item/asset-stock-item.hbs
  app/templates/components/modals/add-notes.hbs
  app/templates/components/modals/ats-add-applicant.hbs
Labels: bug, review

#441 [Enhancement] Sort location, department, supervisor a-z & add search
  app/routes/account/employee/index/edit/job.js
  app/routes/account/employee/onboard/job-information.js
  app/templates/account/employee/index/edit/job.hbs
  app/templates/account/employee/onboard/job-information.hbs
Labels: awaiting submitter action, enhancement, review
