Repository associatedemployers/granite, pull requests merged in 2019-10, with the labels that each got.

#690 [Bug] [Enhancement] Applicant label has no default color even though black displays
  app/components/modals/ats-add-label.js
  app/templates/components/input/quick-form-input.hbs
Labels: bug, enhancement

#691 [Bug] Changes count flag is sticking
  app/routes/account/employees.js
  app/routes/account/employees/changes.js
Labels: bug

#658 [Bug] Recruiting Pipeline applicant schedule meeting doesn't update to show the 'next' meeting
  app/components/card-pipeline/stage-card.js
  app/controllers/account/job-opening/campaign/applicant-tracking.js
  app/templates/account/employee/index.hbs
  app/templates/account/job-opening/campaign/applicant-tracking.hbs
  app/templates/components/card-pipeline.hbs
  app/templates/components/card-pipeline/stage-column.hbs
  app/templates/components/input/date-range.hbs
  app/templates/components/modals/ats-scheduler.hbs
Labels: bug

#713 [Enhancement] Campaign status bar
  app/components/recruiting-status-bar.js
  app/routes/account/job-opening/campaign/index.js
  app/templates/account/job-opening/campaign/index.hbs
  app/templates/components/recruiting-status-bar.hbs
  package.json
Labels: enhancement
