Repository associatedemployers/granite, pull requests merged in 2019-03, with the labels that each got.

#505 Upgrade ember-cli
  .eslintrc.js
  .gitignore
  app/templates/account/settings/index/index.hbs
  package.json
  yarn.lock
Labels: review

#506 [Enhancement] remove social links from contact page
  app/styles/granitestyles/page/contact.less
  app/templates/contact.hbs
  tests/acceptance/main-page-and-sub-pages/contact-page-test.js
Labels: review

#521 [Feature] Source maps #510
  app/routes/account/action-item/index.js
  config/deploy.js
  config/environment.js
  ember-cli-build.js
  package.json
  yarn.lock
Labels: review

#522 [Feature] Add TOS page
  app/router.js
  app/routes/terms-of-service.js
  app/styles/granitestyles/ui/footer.less
  app/templates/components/elements/x-footer.hbs
  app/templates/terms-of-service.hbs
Labels: review

#525 [Chore] update pricing structure
  app/templates/pricing.hbs
Labels: review

#524 [Fix] meeting duration needed
  app/components/modals/ats-add-applicant.js
  app/routes/account/settings/templates/add.js
  app/styles/granitestyles/components/pipeline.less
  app/templates/components/modals/ats-scheduler.hbs
Labels: review

#523 [Feature] [WIP] support page
  app/config/help.js
  app/controllers/account/help/index.js
  app/controllers/application.js
  app/router.js
  app/routes/account/help.js
  app/routes/account/help/index.js
  app/routes/account/help/topic.js
  app/templates/account/help.hbs
  app/templates/account/help/index.hbs
  app/templates/account/help/topic.hbs
  app/templates/terms-of-service.hbs
Labels: WIP, review

#527 [Feature] Add promo code entry
  app/controllers/signup/billing.js
  app/models/company.js
  app/templates/components/input/ui-input.hbs
  app/templates/signup/billing.hbs
  mirage/config.js
  mirage/models/discount.js
  tests/acceptance/signup-test.js
Labels: review

#528 [Enhancement] Change action items to projects
  app/config/breadcrumb.js
  app/controllers/application.js
  app/router.js
  app/routes/account/action-item/index.js
  app/routes/account/action-items/index.js
  app/routes/account/action-items/new.js
  app/services/search.js
  app/templates/account/action-item.hbs
  app/templates/account/action-item/edit.hbs
  app/templates/account/action-items/index.hbs
  app/templates/account/action-items/new.hbs
  tests/acceptance/action-items/action-item-test.js
  tests/acceptance/action-items/action-items-test.js
  tests/acceptance/action-items/edit-action-item-test.js
  tests/acceptance/action-items/new-action-item-test.js
Labels: review

#526 [Enhancement] Add listing url link to recruiting campaigns
  app/components/list-item/job-opening-item.js
  app/models/job-opening.js
  app/templates/account/recruiting/index/index.hbs
  app/templates/components/list-item/job-opening-item.hbs
  tests/acceptance/recruiting/campaigns-test.js
Labels: enhancement, review

#533 [Enhancement] Display costPerCycle on automatic sources
  app/models/applicant-source.js
  app/templates/components/list-item/applicant-source-select.hbs
Labels: review

#531 [Feature] option to not notify applicant of meeting
  app/models/event.js
  app/templates/components/modals/ats-scheduler.hbs
Labels: review

#534 [Enhancement] switch to beta logos
  app/components/elements/company-navigation.js
  app/styles/granitestyles/components/elements/nav.less
  app/styles/granitestyles/global/logos.less
  public/assets/images/beta_granite-logo-mountains-washout-white-shadow.png
  public/assets/images/beta_granite-logo-mountains-washout-white.png
  public/assets/images/beta_granite-logo-mountains.png
Labels: review

#536 [Feature] Add ability to add/edit resume/email on job application
  app/controllers/account/job-opening/campaign/applicant-tracking.js
  app/controllers/account/job-opening/campaign/job-application/edit.js
  app/router.js
  app/routes/account/job-opening/campaign/job-application.js
  app/routes/account/job-opening/campaign/job-application/edit.js
  app/styles/granitestyles/page/job-applacation.less
  app/templates/account/job-opening/campaign/job-application.hbs
  app/templates/account/job-opening/campaign/job-application/edit.hbs
  mirage/config.js
Labels: feature, review

#537 [Enhancement] Refactor dashboard
  .template-lintrc.js
  app/components/list-item/dashboard/continue-action.js
  app/components/list-item/dashboard/project-activity.js
  app/components/list-item/dashboard/todo-item.js
  app/controllers/account/index.js
  app/routes/account/index.js
  app/styles/granitestyles/global/typography.less
  app/styles/granitestyles/page/dashboard.less
  app/templates/account/anatomy/company-users/new.hbs
  app/templates/account/index.hbs
  app/templates/components/list-item/activity-item.hbs
  app/templates/components/list-item/dashboard/continue-action.hbs
  app/templates/components/list-item/dashboard/project-activity.hbs
  app/templates/components/list-item/dashboard/todo-item.hbs
  mirage/config.js
  public/assets/images/beta_granite-logo-mountains copy.png
  tests/integration/components/list-item/dashboard/continue-action-test.js
  tests/integration/components/list-item/dashboard/project-activity-test.js
Labels: review

#539 [Feature] Sharable job apps
  app/components/modals/ats-link-sharing.js
  app/controllers/account/job-opening/campaign/applicant-tracking.js
  app/controllers/application.js
  app/controllers/shared/job-application.js
  app/models/job-application.js
  app/router.js
  app/routes/shared.js
  app/routes/shared/job-application.js
  app/styles/granitestyles/page/shared.less
  app/templates/account/job-opening/campaign/applicant-tracking.hbs
  app/templates/application.hbs
  app/templates/components/card-pipeline.hbs
  app/templates/components/card-pipeline/stage-card.hbs
  app/templates/components/card-pipeline/stage-column.hbs
  app/templates/components/modals/ats-link-sharing.hbs
  app/templates/shared.hbs
  app/templates/shared/job-application.hbs
  tests/acceptance/recruiting/applicants-test.js
Labels: 3 - Review, review

#544 [Enhancement] change "action-item" to "project" on dash
  app/templates/account/index.hbs
Labels: review
