Repository associatedemployers/granite, pull requests merged in 2019-01, with the labels that each got.

#448 highlight census rows with missing required fields or mismatched lookups
  app/components/census/table-cell.js
  app/components/census/table-row.js
  app/components/list-item/dry-run-employee.js
  app/controllers/account/employees/add/census/review.js
  app/styles/granite/page/census-upload.less
  app/templates/account/employees/add/census/review.hbs
  app/templates/components/census/table-cell.hbs
  app/templates/components/census/table-row.hbs
  app/templates/components/list-item/dry-run-employee.hbs
Labels: review

#454 tests passing again
  mirage/config.js
  mirage/factories/employee.js
  tests/acceptance/documents/document-test.js
  tests/acceptance/employees-test.js
Labels: review

#440 [Enhancement] Add close icon to filters
  app/templates/account/employees/index.hbs
  app/templates/account/recruiting/index/index.hbs
Labels: review

#451 added null to jobtype enums
  app/config/statics.js
Labels: review

#439 [Enhancement] Reflow the org chart to the right
  app/components/visualizations/organization-tree.js
  app/components/visualizations/reorganization-tree.js
Labels: awaiting submitter action, enhancement, review

#445 [Enhancement] Add gender field and employee #
  app/config/statics.js
  app/controllers/account/employee/index/edit/index.js
  app/controllers/account/employees/add/census/review.js
  app/controllers/account/employees/add/new.js
  app/models/employee.js
  app/router.js
  app/routes/account/employee/index/documents.js
  app/templates/account/employee/index/edit/index.hbs
  app/templates/account/employees/add/new.hbs
  public/assets/documents/census-template.xlsx
Labels: awaiting submitter action, enhancement, review

#467 [Fix] accounted for multi select in screening responses
  app/templates/account/job-opening/campaign/job-application/index.hbs
Labels: review

#464 [Enhancement] Make overflow-x more apparent in review census
  app/components/display/visual-overflow-table.js
  app/styles/granite/page/census-upload.less
  app/templates/account/employees/add/census/review.hbs
  app/templates/components/display/visual-overflow-table.hbs
Labels: review

#461 [Fix] equipment assigning modals working now in onboarding
  app/components/modals/add-asset-category.js
  app/controllers/account/employee/onboard/equipment.js
Labels: review

#446 changed text editor when creating job descriptions
  app/controllers/account/recruiting/job-descriptions/new.js
  app/templates/components/input/quick-form-input.hbs
Labels: awaiting submitter action, review

#432 [Enhancement] #431 catch enumerable errors to fields in census
  app/components/census/table-cell.js
  app/controllers/account/employees/add/census/review.js
  app/styles/granite/global/application.less
  app/styles/granite/page/census-upload.less
  app/templates/components/census/table-cell.hbs
  app/templates/components/display/visual-overflow-table.hbs
Labels: awaiting submitter action, enhancement, review
